### ISSUE TITLE
Consider switching dependencies from moment.js to date-fns

### ISSUE THREAD

**Issue by jackpilowsky** [react-component/time-picker#130]
For me,  the amount of size that moment.js adds to my builds is unmanageable. There are other issues:

https://github.com/date-fns/date-fns/issues/275#issuecomment-264934189

Date-fns has some very good endorsements: 

https://twitter.com/dan_abramov/status/805030922785525760?lang=en

Would you consider, if I were to submit a pull request to switch the dependency from moment.js to date-fns?

**Comment by dnizetic** [comment]
+1.

**Comment by kkomelin** [comment]
I've just [migrated](https://github.com/kkomelin/time-picker/commit/462c69fc37bb7a2c18f727e874f1f3356c2d8ad7) the project to `date-fns` and the native `Date` type https://github.com/kkomelin/time-picker
- See what has changed for the end-user [here](https://github.com/kkomelin/time-picker/commit/462c69fc37bb7a2c18f727e874f1f3356c2d8ad7#diff-04c6e90faac2675aa89e2176d2eec7d8).
- The Storybook examples work as expected `npm start`.
- Most of the automated tests are successful `npm test`. There are a couple of failed. **Need help with fixing them.**

To play with the project, install it with `npm i https://github.com/kkomelin/time-picker`

### Roadmap
- [x] Perform migration from `Moment.js` to `date-fns`.
- [ ] Fix the failed automated tests. **Need help with this task.**
- [ ] Discuss with `react-component/time-picker` maintainers whether we release a new major version or keep two projects separate.
- [ ] Depending on the results of the discussion, send PR to `react-component/time-picker` or release a new project.

**I would appreciate your feedback and any help with testing and optimizing the code.**

**Comment by behagoras** [comment]
@kkomelin cannot run your fork 😭

**Comment by kkomelin** [comment]
> @kkomelin cannot run your fork

@behagoras Why?
